name: Test Products

on:
  pull_request:
    branches: ["main", "develop"]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker compose build geoproc

      - name: Test Build
        run: docker compose run --rm --entrypoint "python3 -m pytest -v --html=./docs/index.html --self-contained-html" geoproc

      # - name: Commit Changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
