name: Test Products

on:
  pull_request:
    branches: ["main", "develop", "test", "prod"]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Run Tests
      #   run: ./docker_run.sh -tb -a "TEST_DATA_TAG=2025-01-31"

      - name: Build Image
        run: docker compose build

      - name: Test Build
        run: docker compose run --entrypoint "python3 -m pytest -v --html=./docs/index.html --self-contained-html" geoproc

      - name: Commit Changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
